### ISSUE TITLE
How do I generate comparison data with a trained model?

### ISSUE THREAD

**Issue by SoapJohnMacTavish** [baturaysaglam/RIS-MISO-Deep-Reinforcement-Learning#12]
Appreciate your contribution. I am a beginner in the DRL field, and I noticed that the project only provides training code, so how do I use the trained model? For example, how can I use the code of this project to run diagrams such as 4_reproduced.jpg, 5_reproduced.jpg, and 9_reproduced.jpg? More specifically, how can I get the data that leads to these graphs?

**Comment by baturaysaglam** [comment]
I'm not the author of the paper. this repo just reproduces the results independently. all of the data used to generate the curves given in the paper is available [here](https://github.com/baturaysaglam/RIS-MISO-Deep-Reinforcement-Learning/tree/main/Learning%20Curves) NumPy arrays. let me know if there's anything else.
