### ISSUE TITLE
Questions in 'DDPG.py' and 'environment.py'

### ISSUE THREAD

**Issue by ChaiShiMei** [baturaysaglam/RIS-MISO-Deep-Reinforcement-Learning#13]
Dear Mr. Baturay Saglam,

I have some questions regarding to 'DDPG.py' and 'environment.py' .
In 'DDPG.py', I think the codes of lines 47-52 and 65-67 aiming to normalize the phase shift matrix are wrong. Because the norm of the phase after normalization is not equal to 1 ( Actually much less than 1).   

In 'environment.py', in line 114 , is the power '**2' necessary? Because 'self.G.conjugate().T @ self.G' is already the power.  Meanwhile, in line 90, why do you multiply the noise power 'self.awgn_var' with '(self.K - 1)'? 

Could you please double-check these three places?

**Comment by baturaysaglam** [comment]
please take a look at [here](https://github.com/baturaysaglam/RIS-MISO-Deep-Reinforcement-Learning/issues/7).
