### ISSUE TITLE
Help need for Figure 4 and data you generated 

### ISSUE THREAD

**Issue by Amjad-iqbal3** [baturaysaglam/RIS-MISO-Deep-Reinforcement-Learning#14]
I have been diligently working on this code, and currently, I find myself at an impasse regarding the generation of Figure 4 data. Could you kindly shed some light on the process you employed to generate the data for the "Sum_rate_power" folder? If it's not too much to ask, I would greatly appreciate it if you could pinpoint the relevant sections within the code.

Additionally, I am curious about the contents of the "result.npy" file present in the "sum_rate_ris" folder. I'm wondering if these values correspond to the optimal reward (opt_reward) or if they were derived from an alternative source. I would be immensely grateful if you could furnish me with the comprehensive code that facilitated the creation of these two folders. A step-by-step breakdown of the process would be invaluable in aiding my understanding.

Thank you immensely for your assistance.

**Comment by Amjad-iqbal3** [comment]
Dear baturaysaglam
I have been diligently working on this code, and currently, I find myself at an impasse regarding the generation of Figure 4 data. Could you kindly shed some light on the process you employed to generate the data for the "Sum_rate_power" folder? If it's not too much to ask, I would greatly appreciate it if you could pinpoint the relevant sections within the code.

Additionally, I am curious about the contents of the "result.npy" file present in the "sum_rate_ris" folder. I'm wondering if these values correspond to the optimal reward (opt_reward) or if they were derived from an alternative source. I would be immensely grateful if you could furnish me with the comprehensive code that facilitated the creation of these two folders. A step-by-step breakdown of the process would be invaluable in aiding my understanding.

Thank you immensely for your assistance.

**Comment by baturaysaglam** [comment]
I'll try to give a general answer.

**data:** all of the data used were generated by the learning RL agent. so, there's no "generation" in reality. those are the rewards achieved by the learning RL agent.

**generating the figures:** there's no special way to plot those data (i.e., the instantaneous rewards achieved by the agent). I used [matplotlib](https://matplotlib.org/) and I suggest you study the documentation just for designing the plots as you like. 

**step-by-step process of everything:** I've already given the step-by-step to generate anything on the repo except generating the plots. in conclusion, all of the data were the result of the trainings I performed, in a form of the intermediate rewards received by the agent. 

please let me know if anything else.

**Comment by Zainmustafajajja** [comment]
Dear @baturaysaglam  and @Amjad-iqbal3,
I have been working on this code for a while and i am also stuck at same issue for figure no 4. How did you generate data (result.npy file) to produce this figure. Because in code there is no option to generate this data. Have you done it mannualy to match the result in paper?
Please let me know if anyone has an idea.
