### ISSUE TITLE
I have the doubt that i can't re current the results similar to the papers.

### ISSUE THREAD

**Issue by Glen9010** [baturaysaglam/RIS-MISO-Deep-Reinforcement-Learning#5]
I have downloaded this projects and run it. I found that in the first eps , the results can reach 9 or higher. But in the  later eps, the result was stuck in about 1 to 4, this question puzzled me for a long time.

**Comment by Glen9010** [comment]
if the agent is deployed in the real world and the channels is fast time-varying stochastic process， does  it still need train for a long time maybe one or more episode ?
Or this agent is designed for the static channels？

**Comment by baturaysaglam** [comment]
check these issues: [issue 1](https://github.com/baturaysaglam/RIS-MISO-Deep-Reinforcement-Learning/issues/1) [issue 3](https://github.com/baturaysaglam/RIS-MISO-Deep-Reinforcement-Learning/issues/3). I gave the corresponding answer previously.

**Comment by baturaysaglam** [comment]
to answer the question regarding channel representation, I suggest you read the paper. I'm not the author of the paper. but all I can say is if RL is used for learning, then the environment (channel) is assumed to be represented by a Markov Decision Process, which is a discrete-time stochastic control process.
